name: Cordova Nightly

on:
  workflow_dispatch:
    inputs:
      dispatchReason:
        description: 'Reason of Manual Dispatch'
        required: true
        default: 'Re-run broken nightly build'

      verbose:
        description: 'Enable Verbose'
        required: true
        default: 'false'

  schedule:
    - cron: '*/15 * * * *'
    inputs:
      dispatchReason:
        description: 'Reason of Manual Dispatch'
        required: true
        default: 'Default nightly build'

      verbose:
        description: 'Enable Verbose'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Dispatch Inputs
        run: |
          echo "Dispatch Reason: ${{ github.event.inputs.dispatchReason }}"
          echo "Enable Verbose: ${{ github.event.inputs.verbose }}"

      - name: Cordova Coho - Setup
        run: |
          npm i
          npm link

      - name: Cordova Coho - Create Nightlies
        run: |
          cd ..
          coho nightly \
            -r cli \
            -r lib \
            -r common \
            -r fetch \
            -r serve \
            -r create \
            -r node-xcode \
            -r android \
            -r electron \
            -r ios \
            --pretend \
            --verbose ${{ github.event.inputs.verbose == 'true' }}

      - name: NPM Publish - cordova-cli
        run: |
          cd ../cordova-cli
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-lib
        run: |
          cd ../cordova-lib
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-common
        run: |
          cd ../cordova-common
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-fetch
        run: |
          cd ../cordova-fetch
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-serve
        run: |
          cd ../cordova-serve
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-create
        run: |
          cd ../cordova-create
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-node-xcode
        run: |
          cd ../cordova-node-xcode
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-android
        run: |
          cd ../cordova-android
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-electron
        run: |
          cd ../cordova-electron
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-ios
        run: |
          cd ../cordova-ios
          echo "npm publish --tag nightly"
