name: "Cordova Nightly"
on: [push]
  # schedule:
  #   - cron: "*/1 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Environment Variable Setup
        run: echo "Targeted Cordova Packages:\n$( printf '  - %s\n' "${CDV_TARGETS[@]}" )" 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CDV_TARGETS_STRING: "cli:lib:common:fetch:serve:create:node-xcode:android:electron:ios"

      - name: Setup Coho
        run: |
          npm i
          npm link
          cd ..

      - name: Run Coho Nightly
        run: |
          CDV_TARGETS=$(echo $CDV_TARGETS_STRING | tr ":" "\n")
          echo "$( printf '-r %s ' "${CDV_TARGETS[@]}" )--pretend" | xargs coho nightly

      - name: NPM Publish Cordova Packages
        run: |
          CDV_TARGETS=$(echo $CDV_TARGETS_STRING | tr ":" "\n")
          for target in "${CDV_TARGETS[@]}"
          do
            echo "Publishing cordova-${target}"
            echo "changing working directory to cordova-${target}"
            echo "npm is publishing tag nightly"
            echo "changing working directory back to parent"
          done
