name: "Cordova Nightly"

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cordova Coho - Setup
        run: |
          npm i
          npm link

      - name: Cordova Coho - Create Nightlies
        run: |
          cd ..
          coho nightly \
            -r cli \
            -r lib \
            -r common \
            -r fetch \
            -r serve \
            -r create \
            -r node-xcode \
            -r android \
            -r electron \
            -r ios \
            --pretend

      - name: NPM Publish - cordova-cli
        run: |
          cd ../cordova-cli
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-lib
        run: |
          cd ../cordova-lib
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-common
        run: |
          cd ../cordova-common
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-fetch
        run: |
          cd ../cordova-fetch
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-serve
        run: |
          cd ../cordova-serve
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-create
        run: |
          cd ../cordova-create
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-node-xcode
        run: |
          cd ../cordova-node-xcode
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-android
        run: |
          cd ../cordova-android
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-electron
        run: |
          cd ../cordova-electron
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-ios
        run: |
          cd ../cordova-ios
          pwd
          echo "npm publish --tag nightly"
