name: "Cordova Nightly"
on: [push]
  # schedule:
  #   - cron: "*/1 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Environment Variable Setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Coho
        run: |
          pwd
          npm i
          npm link
          cd ..
          pwd

      - name: Run Coho Nightly
        run: |
          echo "coho nightly -r cli -r lib -r common -r fetch -r serve -r create -r node-xcode -r android -r electron -r ios --pretend"

      - name: Publish NPM Packages cordova-cli
        run: |
          pwd
          echo "changing working directory to cordova-cli"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-lib
        run: |
          pwd
          echo "changing working directory to cordova-lib"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-common
        run: |
          pwd
          echo "changing working directory to cordova-common"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-fetch
        run: |
          pwd
          echo "changing working directory to cordova-fetch"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-serve
        run: |
          pwd
          echo "changing working directory to cordova-serve"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-create
        run: |
          pwd
          echo "changing working directory to cordova-create"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-node-xcode
        run: |
          pwd
          echo "changing working directory to cordova-node-xcode"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-android
        run: |
          pwd
          echo "changing working directory to cordova-android"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-electron
        run: |
          pwd
          echo "changing working directory to cordova-electron"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd

      - name: Publish NPM Packages cordova-ios
        run: |
          pwd
          echo "changing working directory to cordova-ios"
          pwd
          echo "npm is publishing tag nightly"
          echo "changing working directory back to parent"
          pwd
