name: "Cordova Nightly"

on: [push]
  # schedule:
  #   - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cordova Coho - Setup
        run: |
          npm i
          npm link

      - name: Cordova Coho - Create Nightlies
        run: |
          cd ..
          coho nightly \
            -r cli \
            -r lib \
            -r common \
            -r fetch \
            -r serve \
            -r create \
            -r node-xcode \
            -r android \
            -r electron \
            -r ios \
            --pretend

      # All the mkdir in the following steps are mocks.
      # They will be removed as the step above will actually make these dirs.
      - name: NPM Publish - cordova-cli
        run: |
          cd ..
          mkdir cordova-cli
          cd cordova-cli
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-lib
        run: |
          cd ..
          mkdir cordova-lib
          cd cordova-lib
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-common
        run: |
          cd ..
          mkdir cordova-common
          cd cordova-common
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-fetch
        run: |
          cd ..
          mkdir cordova-fetch
          cd cordova-fetch
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-serve
        run: |
          cd ..
          mkdir cordova-serve
          cd cordova-serve
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-create
        run: |
          cd ..
          mkdir cordova-create
          cd cordova-create
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-node-xcode
        run: |
          cd ..
          mkdir cordova-node-xcode
          cd cordova-node-xcode
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-android
        run: |
          cd ..
          mkdir cordova-android
          cd cordova-android
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-electron
        run: |
          cd ..
          mkdir cordova-electron
          cd cordova-electron
          pwd
          echo "npm publish --tag nightly"

      - name: NPM Publish - cordova-ios
        run: |
          cd ..
          mkdir cordova-ios
          cd cordova-ios
          pwd
          echo "npm publish --tag nightly"
